import { HouseholdRecord } from "./types"

export const sampleRecordsSolo: HouseholdRecord[] = [
  {
    id: "r1",
    type: "advance",
    amount: 4280,
    date: "2026-03-15",
    label: "スーパー買い物",
    memo: "夕食の材料",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    owner: "self",
  },
  {
    id: "r2",
    type: "advance",
    amount: 2150,
    date: "2026-03-14",
    label: "ドラッグストア",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    owner: "self",
  },
  {
    id: "r3",
    type: "deposit",
    amount: 1500,
    date: "2026-03-13",
    label: "お釣り預かり",
    hasReceipt: false,
    status: "active",
    owner: "self",
  },
  {
    id: "r4",
    type: "advance",
    amount: 8900,
    date: "2026-03-10",
    label: "外食（ランチ会）",
    memo: "同僚との会食",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    owner: "self",
  },
  {
    id: "r5",
    type: "settlement",
    amount: 5000,
    date: "2026-03-08",
    label: "精算",
    hasReceipt: false,
    status: "active",
    owner: "self",
  },
  {
    id: "r6",
    type: "advance",
    amount: 12400,
    date: "2026-02-28",
    label: "電気代",
    memo: "2月分",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    owner: "self",
  },
  {
    id: "r7",
    type: "advance",
    amount: 3200,
    date: "2026-02-25",
    label: "ガソリン代",
    hasReceipt: true,
    receiptCount: 1,
    status: "modified",
    relatedRecordId: "r7m",
    owner: "self",
  },
  {
    id: "r7m",
    type: "advance",
    amount: 3500,
    date: "2026-02-25",
    label: "ガソリン代（修正）",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    relatedRecordId: "r7",
    owner: "self",
  },
  {
    id: "r8",
    type: "deposit",
    amount: 2000,
    date: "2026-02-20",
    label: "図書カード預かり",
    hasReceipt: false,
    status: "cancelled",
    relatedRecordId: "r8c",
    owner: "self",
  },
]

export const sampleRecordsManaged: HouseholdRecord[] = [
  {
    id: "m1",
    type: "advance",
    amount: 4280,
    date: "2026-03-15",
    label: "スーパー買い物",
    memo: "夕食の材料",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    approvalStatus: "approved",
    owner: "self",
  },
  {
    id: "m2",
    type: "advance",
    amount: 6500,
    date: "2026-03-14",
    label: "子供の文房具",
    hasReceipt: true,
    receiptCount: 2,
    status: "active",
    approvalStatus: "pending",
    owner: "self",
  },
  {
    id: "m3",
    type: "deposit",
    amount: 1500,
    date: "2026-03-13",
    label: "お釣り預かり",
    hasReceipt: false,
    status: "active",
    approvalStatus: "rejected",
    rejectionComment: "金額を確認してください。1,500円ではなく1,800円だったと思います。",
    owner: "self",
  },
  {
    id: "m4",
    type: "advance",
    amount: 8900,
    date: "2026-03-10",
    label: "外食（ランチ会）",
    memo: "同僚との会食",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    approvalStatus: "approved",
    owner: "self",
  },
  {
    id: "m5",
    type: "settlement",
    amount: 5000,
    date: "2026-03-08",
    label: "精算",
    hasReceipt: false,
    status: "active",
    approvalStatus: "approved",
    owner: "self",
  },
]

export const samplePartnerRecords: HouseholdRecord[] = [
  {
    id: "p1",
    type: "advance",
    amount: 3800,
    date: "2026-03-15",
    label: "コンビニ買い物",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    approvalStatus: "pending",
    owner: "partner",
  },
  {
    id: "p2",
    type: "advance",
    amount: 15000,
    date: "2026-03-12",
    label: "子供の習い事",
    memo: "3月分月謝",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    approvalStatus: "pending",
    owner: "partner",
  },
  {
    id: "p3",
    type: "deposit",
    amount: 5000,
    date: "2026-03-10",
    label: "ATM引き出し預かり",
    hasReceipt: false,
    status: "active",
    approvalStatus: "approved",
    owner: "partner",
  },
  {
    id: "p4",
    type: "advance",
    amount: 2480,
    date: "2026-03-08",
    label: "クリーニング代",
    hasReceipt: true,
    receiptCount: 1,
    status: "active",
    approvalStatus: "approved",
    owner: "partner",
  },
  {
    id: "p5",
    type: "settlement",
    amount: 8000,
    date: "2026-03-05",
    label: "精算",
    hasReceipt: false,
    status: "active",
    approvalStatus: "approved",
    owner: "partner",
  },
]
