import { HouseholdEntry, DisplayImage } from "./types"

/** モック用の画像データ生成ヘルパー */
function mockImage(id: string): DisplayImage {
  return {
    id,
    thumbnailUrl: `/mock-images/${id}-thumb.jpg`,
    fullUrl: `/mock-images/${id}-full.jpg`,
    loadState: "loaded",
  }
}

function mockImageLoading(id: string): DisplayImage {
  return {
    id,
    thumbnailUrl: `/mock-images/${id}-thumb.jpg`,
    fullUrl: `/mock-images/${id}-full.jpg`,
    loadState: "loading",
  }
}

function mockImageError(id: string): DisplayImage {
  return {
    id,
    thumbnailUrl: `/mock-images/${id}-thumb.jpg`,
    fullUrl: `/mock-images/${id}-full.jpg`,
    loadState: "error",
  }
}

export const sampleEntriesSolo: HouseholdEntry[] = [
  {
    id: "r1",
    type: "advance",
    amount: 4280,
    occurredOn: "2026-03-15",
    createdAt: "2026-03-15T12:30:00Z",
    label: "スーパー買い物",
    memo: "夕食の材料",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("r1-img1")],
    status: "active",
    owner: "self",
  },
  {
    id: "r2",
    type: "advance",
    amount: 2150,
    occurredOn: "2026-03-14",
    createdAt: "2026-03-14T18:00:00Z",
    label: "ドラッグストア",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("r2-img1")],
    status: "active",
    owner: "self",
  },
  {
    id: "r3",
    type: "deposit",
    amount: 1500,
    occurredOn: "2026-03-13",
    createdAt: "2026-03-13T10:15:00Z",
    label: "お釣り預かり",
    hasReceipt: false,
    status: "active",
    owner: "self",
  },
  {
    id: "r4",
    type: "advance",
    amount: 8900,
    occurredOn: "2026-03-10",
    createdAt: "2026-03-10T20:45:00Z",
    label: "外食（ランチ会）",
    memo: "同僚との会食",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("r4-img1")],
    status: "active",
    owner: "self",
  },
  {
    id: "r5",
    type: "settlement",
    amount: 5000,
    occurredOn: "2026-03-08",
    createdAt: "2026-03-08T09:00:00Z",
    label: "精算",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("r5-img1")],
    status: "active",
    owner: "self",
  },
  {
    id: "r6",
    type: "advance",
    amount: 12400,
    occurredOn: "2026-02-28",
    createdAt: "2026-03-01T08:30:00Z",
    label: "電気代",
    memo: "2月分",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("r6-img1")],
    status: "active",
    owner: "self",
  },
  {
    id: "r7m",
    type: "advance",
    amount: 3500,
    occurredOn: "2026-02-25",
    createdAt: "2026-02-27T14:00:00Z",
    label: "ガソリン代",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("r7m-img1")],
    status: "active",
    relatedEntryId: "r7",
    owner: "self",
  },
  {
    id: "r8",
    type: "deposit",
    amount: 2000,
    occurredOn: "2026-02-20",
    createdAt: "2026-02-20T16:30:00Z",
    label: "図書カード預かり",
    hasReceipt: false,
    status: "cancelled",
    relatedEntryId: "r8c",
    owner: "self",
  },
]

export const sampleEntriesManaged: HouseholdEntry[] = [
  {
    id: "m1",
    type: "advance",
    amount: 4280,
    occurredOn: "2026-03-15",
    createdAt: "2026-03-15T12:30:00Z",
    label: "スーパー買い物",
    memo: "夕食の材料",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("m1-img1")],
    status: "active",
    approvalStatus: "approved",
    owner: "self",
  },
  {
    id: "m2",
    type: "advance",
    amount: 6500,
    occurredOn: "2026-03-14",
    createdAt: "2026-03-14T19:00:00Z",
    label: "子供の文房具",
    hasReceipt: true,
    receiptCount: 2,
    images: [mockImage("m2-img1"), mockImage("m2-img2")],
    status: "active",
    approvalStatus: "pending",
    owner: "self",
  },
  {
    id: "m3",
    type: "deposit",
    amount: 1500,
    occurredOn: "2026-03-13",
    createdAt: "2026-03-13T10:15:00Z",
    label: "お釣り預かり",
    hasReceipt: false,
    status: "active",
    approvalStatus: "rejected",
    rejectionComment: "金額を確認してください。1,500円ではなく1,800円だったと思います。",
    owner: "self",
  },
  {
    id: "m4",
    type: "advance",
    amount: 8900,
    occurredOn: "2026-03-10",
    createdAt: "2026-03-10T20:45:00Z",
    label: "外食（ランチ会）",
    memo: "同僚との会食",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("m4-img1")],
    status: "active",
    approvalStatus: "approved",
    owner: "self",
  },
  {
    id: "m5",
    type: "settlement",
    amount: 5000,
    occurredOn: "2026-03-08",
    createdAt: "2026-03-08T09:00:00Z",
    label: "精算",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("m5-img1")],
    status: "active",
    approvalStatus: "approved",
    owner: "self",
  },
  {
    id: "m6m",
    type: "advance",
    amount: 3500,
    occurredOn: "2026-02-25",
    createdAt: "2026-02-27T14:00:00Z",
    label: "ガソリン代",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("m6m-img1")],
    status: "active",
    approvalStatus: "approved",
    relatedEntryId: "m6",
    owner: "self",
  },
  {
    id: "m7",
    type: "deposit",
    amount: 2000,
    occurredOn: "2026-02-20",
    createdAt: "2026-02-20T16:30:00Z",
    label: "図書カード預かり",
    hasReceipt: false,
    status: "cancelled",
    owner: "self",
  },
]

export const samplePartnerEntries: HouseholdEntry[] = [
  {
    id: "p1",
    type: "advance",
    amount: 3800,
    occurredOn: "2026-03-15",
    createdAt: "2026-03-15T14:00:00Z",
    label: "コンビニ買い物",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("p1-img1")],
    status: "active",
    approvalStatus: "pending",
    owner: "partner",
  },
  {
    id: "p2",
    type: "advance",
    amount: 15000,
    occurredOn: "2026-03-12",
    createdAt: "2026-03-12T10:00:00Z",
    label: "子供の習い事",
    memo: "3月分月謝",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("p2-img1")],
    status: "active",
    approvalStatus: "pending",
    owner: "partner",
  },
  {
    id: "p3",
    type: "deposit",
    amount: 5000,
    occurredOn: "2026-03-10",
    createdAt: "2026-03-10T11:30:00Z",
    label: "ATM引き出し預かり",
    hasReceipt: false,
    status: "active",
    approvalStatus: "approved",
    owner: "partner",
  },
  {
    id: "p4",
    type: "advance",
    amount: 2480,
    occurredOn: "2026-03-08",
    createdAt: "2026-03-08T17:20:00Z",
    label: "クリーニング代",
    hasReceipt: true,
    receiptCount: 1,
    images: [mockImage("p4-img1")],
    status: "active",
    approvalStatus: "approved",
    owner: "partner",
  },
  {
    id: "p5",
    type: "settlement",
    amount: 8000,
    occurredOn: "2026-03-05",
    createdAt: "2026-03-05T09:00:00Z",
    label: "精算",
    hasReceipt: true,
    receiptCount: 2,
    images: [mockImage("p5-img1"), mockImage("p5-img2")],
    status: "active",
    approvalStatus: "approved",
    owner: "partner",
  },
]
