#!/bin/bash
set -euo pipefail

WORKTREE_ROOT="$(git rev-parse --show-toplevel)"
MAIN_ROOT="$(git rev-parse --path-format=absolute --git-common-dir | xargs dirname)"

cd "$WORKTREE_ROOT"

echo "=== worktree setup ==="
echo "Worktree: $WORKTREE_ROOT"
echo ""

# --------------------------------------------------
# 1. Install dependencies
# --------------------------------------------------
echo "[1/3] Installing dependencies..."
pnpm install

# --------------------------------------------------
# 2. Determine ports
# --------------------------------------------------
if [ "$WORKTREE_ROOT" = "$MAIN_ROOT" ]; then
  API_PORT=8787
  EXPO_PORT=8081
else
  HASH=$(echo "$WORKTREE_ROOT" | cksum | cut -d' ' -f1)
  API_PORT=$(( (HASH % 1000) + 8800 ))
  EXPO_PORT=$(( API_PORT + 1000 ))
fi

echo "[2/3] Port assignment: API=${API_PORT}, Expo=${EXPO_PORT}"

# .env.worktree (root)
cat > .env.worktree <<EOF
# Auto-generated by scripts/setup-worktree.sh
export API_PORT=${API_PORT}
export EXPO_PORT=${EXPO_PORT}
EOF

# --------------------------------------------------
# 3. Create env files
# --------------------------------------------------
echo "[3/3] Creating env files..."

# Copy env files from main worktree
if [ "$WORKTREE_ROOT" != "$MAIN_ROOT" ]; then
  cp "$MAIN_ROOT/api/.dev.vars" api/.dev.vars
  cp "$MAIN_ROOT/expo/.env" expo/.env
  echo "  api/.dev.vars -> copied from main worktree"
  echo "  expo/.env     -> copied from main worktree"

  # Update ports to match this worktree
  sed -i '' "s|BETTER_AUTH_URL=http://localhost:[0-9]*|BETTER_AUTH_URL=http://localhost:${API_PORT}|" api/.dev.vars
  sed -i '' "s|EXPO_PUBLIC_API_URL=http://localhost:[0-9]*|EXPO_PUBLIC_API_URL=http://localhost:${API_PORT}|" expo/.env
  echo "  Ports updated to ${API_PORT}"
fi

echo ""
echo "=== Setup complete ==="
echo "  API:  http://localhost:${API_PORT}"
echo "  Expo: port ${EXPO_PORT}"
echo ""
echo "Start dev servers:"
echo "  pnpm dev:api"
echo "  pnpm dev:expo"
