#!/bin/bash
set -euo pipefail

WORKTREE_ROOT="$(git rev-parse --show-toplevel)"
MAIN_ROOT="$(git rev-parse --path-format=absolute --git-common-dir | xargs dirname)"

# メインworktreeまたはセットアップ済みなら何もしない
[ "$WORKTREE_ROOT" = "$MAIN_ROOT" ] && exit 0
[ -f "$WORKTREE_ROOT/.env.worktree" ] && exit 0

cd "$WORKTREE_ROOT"

echo "=== worktree setup ===" >&2
echo "Worktree: $WORKTREE_ROOT" >&2
echo "" >&2

# --------------------------------------------------
# 1. Install dependencies
# --------------------------------------------------
echo "[1/3] Installing dependencies..." >&2
pnpm install >&2

# --------------------------------------------------
# 2. Determine ports
# --------------------------------------------------
HASH=$(echo "$WORKTREE_ROOT" | cksum | cut -d' ' -f1)
API_PORT=$(( (HASH % 1000) + 8800 ))
EXPO_PORT=$(( API_PORT + 1000 ))

echo "[2/3] Port assignment: API=${API_PORT}, Expo=${EXPO_PORT}" >&2

cat > .env.worktree <<EOF
# Auto-generated by scripts/setup-worktree.sh
export API_PORT=${API_PORT}
export EXPO_PORT=${EXPO_PORT}
EOF

# --------------------------------------------------
# 3. Copy env files from main worktree
# --------------------------------------------------
echo "[3/3] Creating env files..." >&2

cp "$MAIN_ROOT/api/.dev.vars" api/.dev.vars
cp "$MAIN_ROOT/expo/.env" expo/.env
echo "  api/.dev.vars -> copied from main worktree" >&2
echo "  expo/.env     -> copied from main worktree" >&2

# Update ports to match this worktree
sed -i '' "s|BETTER_AUTH_URL=http://localhost:[0-9]*|BETTER_AUTH_URL=http://localhost:${API_PORT}|" api/.dev.vars
sed -i '' "s|EXPO_PUBLIC_API_URL=http://localhost:[0-9]*|EXPO_PUBLIC_API_URL=http://localhost:${API_PORT}|" expo/.env
echo "  Ports updated to ${API_PORT}" >&2

echo "" >&2
echo "=== Setup complete ===" >&2
echo "  API:  http://localhost:${API_PORT}" >&2
echo "  Expo: port ${EXPO_PORT}" >&2
echo "" >&2
echo "Start dev servers:" >&2
echo "  pnpm dev:api" >&2
echo "  pnpm dev:expo" >&2
